# specrails-generated Codex permission rules (Starlark)
# Generated by /setup — edit manually if needed
# Reference: https://developers.openai.com/codex/config-reference

# Version control — always allowed
prefix_rule(pattern=["git"], decision="allow")

# GitHub CLI — allowed if detected during setup
prefix_rule(pattern=["gh"], decision="allow")

# Project-specific tool allowances (detected during /setup)
{{CODEX_SHELL_RULES}}
